stages:
  - build

build:
  stage: build
  script:
    - echo "${DRACS_GITLAB_KEY}" > .ssh/git_deploy_key
    - id && ls -l .ssh
    - chmod 400 .ssh/config .ssh/git_deploy_key
    - ./bin/ci/build
  tags:
    - docker-build
