stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - echo "${DRACS_GITLAB_KEY}" > .ssh/git_deploy_key
    - id && ls -l .ssh
    - chmod 400 .ssh/config .ssh/git_deploy_key
    - ./bin/ci/build
  tags:
    - docker-build

jest:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-candidate:${CI_COMMIT_REF_SLUG}
  # by default, gitlab ci clones your code out into a build directory
  # that needs to then be initialized with npm.
  # Since we are testing a candidate image that already has the required modules
  # installed with npm install, we do not need to clone into the build directory.
  # Instead, we need to change into the WORKDIR for the image before we run the
  # tests, and then copy any artifacts back to the original CI_PROJECT_DIR
  variables:
    GIT_STRATEGY: none
  script:
    - cd /opt/app-root/src
    - npm run ci_test
    - mv coverage ${CI_PROJECT_DIR}
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts: # these are saved and available to other jobs in this script even when container is removed
    when: always # see docs for possible values
    paths:
      - coverage/ # where to save
  tags:
    - docker

# this should be turned into a bot that fixes and creates a merge request
security_audit:
  tags:
    - docker
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-candidate:${CI_COMMIT_REF_SLUG}
  variables:
    GIT_STRATEGY: none
  script:
    - cd /opt/app-root/src
    - npm audit
  # temporary until dracs is updated and we can upgrade react, etc
  # as audit can't ignore dev dependencies
  allow_failure: true
  only:
    - master

pages:
  tags:
    - docker
  stage: publish
  dependencies:
    - jest
  script: # move all artifacts from previous jobs to public folder
    - mv coverage/ public/
    - echo "PAGES AVAILABLE AT ${CI_PAGES_URL}"
  artifacts:
    when: always
    paths:
      - public
    expire_in: 30 days
