stages:
  - build
  - test
  - publish
  - check_security
  - deployment

variables:
  LOG_LEVEL: "info"

include:
  - project: 'ori-rad/kubernetes_deployment_pipeline'
    file: '/auto_version.yml'
  - project: 'ori-rad/kubernetes_deployment_pipeline'
    file: '/ori-deployments.yml'

build:
  stage: build
  script:
    - if [ -z "${DRACS_GITLAB_KEY}" ]; then echo "DRACS_GITLAB_KEY ENVIRONMENT IS MISSING"; exit 1; fi
    - echo "${DRACS_GITLAB_KEY}" > .ssh/git_deploy_key
    - chmod 400 .ssh/config .ssh/git_deploy_key
    - ./.ci/bin/build
  only:
    - branches
  tags:
    - shell-executor

jest:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-candidate-${CI_COMMIT_SHA}:${CI_COMMIT_REF_SLUG}
  # by default, gitlab ci clones your code out into a build directory
  # that needs to then be initialized with npm.
  # Since we are testing a candidate image that already has the required modules
  # installed with npm install, we do not need to clone into the build directory.
  # Instead, we need to change into the WORKDIR for the image before we run the
  # tests, and then copy any artifacts back to the original CI_PROJECT_DIR
  variables:
    GIT_STRATEGY: none
  script:
    - cd /opt/app-root/src
    - npm run ci_test
    - mv coverage ${CI_PROJECT_DIR}
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  only:
    - branches
  tags:
    - docker

security_audit:
  tags:
    - docker
  stage: test
  image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}-candidate-${CI_COMMIT_SHA}:${CI_COMMIT_REF_SLUG}
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${APP_ROOT}
    - npm install npm@latest -g --prefix ${APP_ROOT}/.node_modules
    - ${APP_ROOT}/.node_modules/bin/npm i --package-lock-only
    - ${APP_ROOT}/.node_modules/bin/npm audit > audit_report.txt 2>&1
  # temporary until dracs is updated and we can upgrade react, etc
  # as audit can't ignore dev dependencies
  allow_failure: true
  artifacts:
    paths:
      - audit_report.txt
    expire_in: 1 week
  only:
    - master

# this only runs on master
# it automatically generates the next semantic verson and creates an annotated tag
increment_version:
  extends: .auto_version
  stage: publish
  only:
    - master
  tags:
    - docker

publish_development_image:
  stage: publish
  script:
    - ./.ci/bin/build_deployment
  environment:
    name: development
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
  tags:
    - docker-build

publish_uatest_image:
  stage: publish
  script:
    - ./.ci/bin/build_deployment
  environment:
    name: uatest
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^uatest\-v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
  tags:
    - docker-build

scan_development_deployment_image:
  stage: check_security
  variables:
    SCAN_IMAGE_OVERRIDE: "${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  extends: .scan
  environment:
    name: development
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

scan_uatest_deployment_image:
  stage: check_security
  variables:
    SCAN_IMAGE_OVERRIDE: "${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
  extends: .scan
  environment:
    name: uatest
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^uatest\-v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

deploy_development:
  stage: deployment
  extends: .deploy
  environment:
    name: development
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

deploy_uatest:
  stage: deployment
  extends: .deploy
  environment:
    name: uatest
    url: https://${ENVIRONMENT_ROUTE_URL}
  only:
    - /^uatest\-v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
