# build with build args that are not saved in the docker history
# https://vsupalov.com/build-docker-image-clone-private-repo-ssh-key/
FROM node:8-alpine as intermediate

EXPOSE 8080
ENV APP_ROOT=/opt/app-root/src
ENV NODE_ENV=production

ARG OAUTH_CLIENT_ID
ARG OAUTH_REDIRECT
ARG DDS_API_BASE_URL

RUN mkdir -p ${APP_ROOT}
ADD . ${APP_ROOT}

WORKDIR ${APP_ROOT}

# lifted centos/nodejs s2i builder assemble scripts
RUN [ "${NODE_ENV}" == "production" ] && \
    NODE_ENV=development npm install && \
    npm run build --if-present && \
    npm prune && \
    rm $(npm config get cache)* -rf && \
    rm -rf $(npm config get tmp)/npm-* || \
    echo ""

FROM node:8-alpine

ENV APP_ROOT=/opt/app-root/src
ENV NODE_ENV=production

WORKDIR ${APP_ROOT}
COPY --from=intermediate ${APP_ROOT}/app.js ${APP_ROOT}/app.js
COPY --from=intermediate ${APP_ROOT}/node_modules ${APP_ROOT}/node_modules
COPY --from=intermediate ${APP_ROOT}/dist ${APP_ROOT}/dist

RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT}

# lifted centos/nodejs s2i builder fix_permissions script
RUN find -L "${APP_ROOT}" -user 1001 \! -group 0 -exec chgrp 0 {} + && \
    find -L "${APP_ROOT}" -user 1001 \! -perm -g+rw -exec chmod g+rw {} + && \
    find -L "${APP_ROOT}" -user 1001 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} + && \
    find -L "${APP_ROOT}" -user 1001 -type d \! -perm /g+x -exec chmod g+x {} +

USER 1001
CMD node app.js
