version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - OAUTH_CLIENT_ID
        - OAUTH_REDIRECT
        - DDS_API_BASE_URL
    image: dds-api-keys
    command: node app.js
    ports:
      - 8080:8080
