FROM dds-api-keys

ARG OAUTH_CLIENT_ID
ARG OAUTH_REDIRECT
ARG DDS_API_BASE_URL

USER root
# lifted centos/nodejs s2i builder assemble scripts
RUN npm run build --if-present && \
    npm prune && \
    rm $(npm config get cache)* -rf && \
    rm -rf $(npm config get tmp)/npm-*
    RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
        find -L "${APP_ROOT}" -user 1001 \! -group 0 -exec chgrp 0 {} + && \
        find -L "${APP_ROOT}" -user 1001 \! -perm -g+rw -exec chmod g+rw {} + && \
        find -L "${APP_ROOT}" -user 1001 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} + && \
        find -L "${APP_ROOT}" -user 1001 -type d \! -perm /g+x -exec chmod g+x {} +
