FROM node:8-alpine

ARG CI_COMMIT_SHA=unspecified
LABEL git_commit_sha=${CI_COMMIT_SHA}

# twistlock finds old version of tar in npm/node_modules/node-gyp
RUN npm update -g npm && \
    npm explore npm/node_modules/node-gyp -g -- npm install tar@4.4.2

USER 1001
ENV APP_ROOT=/opt/app-root/src
ENV NODE_ENV=production

WORKDIR ${APP_ROOT}
ADD app.js ${APP_ROOT}/app.js
ADD node_modules ${APP_ROOT}/node_modules
ADD dist ${APP_ROOT}/dist

CMD node app.js
