apiVersion: v1
kind: Pod
metadata:
  name: {{ include "dds-api-keys-unit-tests.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dds-api-keys-unit-tests.name" . }}
    helm.sh/chart: {{ include "dds-api-keys-unit-tests.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  restartPolicy: Never
  {{- if .Values.image.pullSecret }}
  imagePullSecrets:
  - name: {{ .Values.image.pullSecret }}
  {{- end }}
  containers:
    - name: {{ .Chart.Name }}
      env:
        - name: NODE_ENV
          value: {{ .Values.environment }}
      image: "{{ .Values.image.repository }}:{{ .Values.environment }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command:
        - /usr/local/bin/npm
        - run
        - ci_test
