apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullName" . }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
    version: {{ .Values.version }}
    git_commit: {{ .Values.git_commit }}
    git_tag: {{ .Values.git_tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      environment: {{ .Values.environment }}
  # This is the pod template
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.version }}
        git_commit: {{ .Values.git_commit }}
    spec:
      containers:
        - name: {{ include "fullName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.port.name }}
              containerPort: {{ .Values.port.number }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.livenessProbe }}
              port: {{ .Values.port.name }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      imagePullSecrets:
        - name: {{ include "fullName" . }}-pull
