apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: {{ template "dds-api-keys.fullname" . }}-pull
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
