apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "fullName" . }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  {{- if .Values.url }}
  host: {{ .Values.url }}
  {{- end }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "fullName" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - wildcardPolicy: None
