apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "dds-api-keys.environmentName" . }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "dds-api-keys.environmentName" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - wildcardPolicy: None
