apiVersion: v1
kind: Service
metadata:
  name: {{ include "dds-api-keys.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.port.name }}
      port: {{ .Values.port.number }}
      targetPort: {{ .Values.port.name }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    environment: {{ .Release.Name }}
